config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :courses, except: [:show]

  resources :sessions, only: [:create, :new, :destroy]

  resources :certificate, only: :index

  resources :prisoners, only: [:create, :update, :show, :index, :edit] do
    resources :units, only: [:create, :update]
  end

  resources :volunteers, only: [:create, :update, :show, :index, :edit]

  resources :units, only: [:update, :show, :index] do
    resources :assigns, only: :update
    resources :volunteers, only: [:show] do
      resources :assigns, only: [:create]
    end
  end
  get 'completed_units' => 'units#completed_units'

  get 'reports/attrs' => 'reports#attrs'
  resources :reports, only: [:index, :show, :create, :new, :destroy]

  get '/sub_course/:id' => 'units#find_sub_courses'
  post '/dictionary' => 'prisoners#dictionary'
  post '/vacation' => 'volunteers#vacation'
  get '/waitlist' => 'prisoners#waitlist'
  get '/late/:days' => 'units#late'
  post '/:prisoner_id/certificate' => 'certificate#create'
  get '/course_overview' => 'static_pages#courses'
  post '/delete_vacation' => 'volunteers#delete_vacation'

  get '/units/destroy/:id' => "api/units#destroy"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@prisoner = Prisoner.new
  	@volunteer = Volunteer.new
    @prisoners = Prisoner.all
  end

  def courses
    @courses = Course.active.order('title ASC')
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def us_states
  	%w(ME AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA PR RI SC SD TN TX UT VA VT WA WI WV WY)
	end
end

app/views/static_pages/courses.html.erb
<% provide :title, "Course Overview" %>

<button class="btn-lg btn-primary new-course-button">
	<%= link_to "New Course", new_course_path %>
</button>

<h3 style="text-align: center;">Course Overview</h3>

<% @courses.each_with_index do |course, i| %>
	<% if (i+1) % 3 == 0 %>
		<div class="col-sm-12"></div>
	<% end %>
	<div class="col-sm-4 ">
		<div class="course-box">
			<h4><%= link_to course.title, edit_course_path(course) %></h4>
			<% course.sub_courses.each do |sub_course| %>
				<p><%= sub_course %></p>
			<% end %>
		</div>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#new-unit">New Student</a></li>
  <li><a data-toggle="tab" href="#new-vol">New Volunteer</a></li>
</ul>

<div class="tab-content">
	<div id="new-unit" class="tab-pane fade in active">
		<div class="why-here">Find or Add Student</div>
		<div class="col-sm-8">
			<%= render 'prisoners/new' %>
		</div>
		<div class="col-sm-4">
			<%= link_to "Student Already Exists", prisoners_path, class: "btn-lg btn-primary" %>
		</div>
	</div>
	<div id="new-vol" class="tab-pane fade">
		<div class="col-sm-8 col-sm-offset-2">
			<%= render 'volunteers/new' %>
		</div>
	</div>
</div>

<div class="col-sm-12">
	<hr>

	<div class="export-link">
		<%= link_to("Export Certificate Data", certificate_index_path(format: :csv)) %>
	</div>
</div>