config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :courses, except: [:show]

  resources :sessions, only: [:create, :new, :destroy]

  resources :certificate, only: :index

  resources :prisoners, only: [:create, :update, :show, :index, :edit] do
    resources :units, only: [:create, :update]
  end

  resources :volunteers, only: [:create, :update, :show, :index, :edit]

  resources :units, only: [:update, :show, :index] do
    resources :assigns, only: :update
    resources :volunteers, only: [:show] do
      resources :assigns, only: [:create]
    end
  end
  get 'completed_units' => 'units#completed_units'

  get 'reports/attrs' => 'reports#attrs'
  resources :reports, only: [:index, :show, :create, :new, :destroy]

  get '/sub_course/:id' => 'units#find_sub_courses'
  post '/dictionary' => 'prisoners#dictionary'
  post '/vacation' => 'volunteers#vacation'
  get '/waitlist' => 'prisoners#waitlist'
  get '/late/:days' => 'units#late'
  post '/:prisoner_id/certificate' => 'certificate#create'
  get '/course_overview' => 'static_pages#courses'
  post '/delete_vacation' => 'volunteers#delete_vacation'

  get '/units/destroy/:id' => "api/units#destroy"

end

app/models/unit.rb
require 'csv'

class Unit < ActiveRecord::Base
  mount_uploader :scan, ScanUploader
  mount_uploader :reader_scan, ReaderScanUploader
  default_scope { order(mailing_date: :desc)}

  # Associations
  belongs_to :course
  belongs_to :prisoner
  belongs_to :volunteer

  # Validations
  # validates :course, presence: true
  # validates :prisoner, presence: true
  # validates :mailing_date, presence: true
  #validates :scan, presence: true

  def self.to_csv
    attributes = %w{course sub_course prisoner volunteer mailing_date return_date reader_mailing_date reader_return_date created_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |unit|
        csv << attributes.map do |attr| 
          if attr == 'course'
            unit.course.try(:title)
          elsif attr == 'volunteer'
            unit.volunteer.try(:name)
          elsif attr == 'prisoner'
            unit.prisoner.try(:name)
          else
            unit.send(attr)
          end
        end
      end
    end
  end

  def self.report_rows
    %w(mailing_date return_date reader_mailing_date reader_return_date)
  end

  def status
    if return_date.nil?
      "Waiting on Student"
    elsif return_date && reader_mailing_date.nil?
      "Unassigned"
    elsif reader_mailing_date && reader_return_date.nil?
      "Waiting on Volunteer"
    elsif reader_return_date
      "Completed"
    end
  end

  def sub_course_abbr
    sub_course.truncate(20) if sub_course
  end

  def speed
    (return_date - mailing_date).to_i
  end

  def late?
    unless return_date
      (Date.today() - mailing_date).to_i >= 7
    end
  end

end

app/controllers/api/units_controller.rb
class Api::UnitsController < ApplicationController
  def destroy
    Unit.find(params[:id]).delete
    redirect_to units_path
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def show
    @unit = Unit.find(params[:id])
    @matches = Volunteer.find_matches(@unit)
    p @matches
    if @unit.status == "Unassigned"
      @title = "Assign"
    end
  end

  def create
   	@prisoner = Prisoner.find(params[:prisoner_id])
  	@unit = @prisoner.units.build(unit_params)
  	if @unit.save
      sub_course = Course.find(params[:unit][:course_id]).sub_courses[params[:unit][:sub_course].to_i]
      @unit.update_attribute(:sub_course, sub_course)
  		redirect_to @unit
  	else
  		render "prisoners/show"
  	end
  end

  def update
    @unit = Unit.find(params[:id])
    @unit.update_attributes(unit_params)
    redirect_to @unit
  end

  def index
    units = Unit.all
    @unassigned = units.select { |x| x.status == "Unassigned" }
    @waiting = units.select { |x| x.status == "Waiting on Volunteer" }
    @waiting_student = units.select { |x| x.status == "Waiting on Student" }

    respond_to do |format|
      format.html
      format.csv { send_data Unit.to_csv, filename: "units-#{Date.today}.csv" }
    end
  end

  def completed_units
    # @units = Unit.where.not(reader_return_date: nil).paginate(:page => params[:page])
    @units = Unit.where.not(reader_return_date: nil)

    # @units = Unit.all.select { |u| u.status == "Completed" }
  end

  def find_sub_courses
    render json: Course.find(params[:id]).sub_courses.to_json
  end

  def late
    @units = Unit.all.select { |unit| unit.reader_mailing_date && unit.reader_mailing_date < (Date.today - 7.days) && unit.reader_return_date.nil? }
  end

  private

  	def unit_params
  		params.require(:unit).permit(:mailing_date, :prison_id, :course_id, :scan, :return_date, :reader_scan, :reader_mailing_date, :reader_return_date)
  	end

end

app/views/units/_create.html.erb
<div id="unit-create">
	<% if @unit.errors.any? %>
		<% @unit.errors.full_messages.each do |error| %>
			<p class="error_text"><%= error %></p>
		<% end %>
	<% end %>
	<%= simple_form_for @unit, url: prisoner_units_path(@prisoner), html: { multipart: true } do |f| %>
		<%= f.input :mailing_date, as: :date %>
		<label>Course</label>
		<select class="form-control select optional" id="course" name="unit[course_id]">
			<option value=""></option>
			<%= Course.active.each do |course| %>
				<option value="<%= course.id %>"><%= course.title %></option>
			<% end %>
		</select>
		<hr>
		<div id="sub_course"></div>
		<%= f.button :submit, class: 'btn btn-warning' %>
	<% end %>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		var picked = false;
		$("#course").change(function(e){
			if (picked) {
				$("#sub_course").empty();
			}
			$.get("/sub_course/" + $(this).val(), function(data, status){
				$("#sub_course").append("<div>* Course Unit</div>");
				$("#sub_course").append("<select id='sub_course_select' class='select required form-control' name='unit[sub_course]' style='margin-bottom:15px;'></select>");
				for (i = 0; i < data.length; i++) {
					$("#sub_course_select").append("<option value=" + i + ">" + data[i] + "</option>")
				}
			})
			picked = true;
		});
	});
</script>

app/views/units/_reader_update.html.erb
<div id="unit-update">
	<h4> When Reader Has Returned Unit</h4>
	<% if @unit.errors.any? %>
		<% @unit.errors.full_messages.each do |error| %>
			<p class="error_text"><%= error %></p>
		<% end %>
	<% end %>
	<%= simple_form_for @unit, url: unit_path(@unit), html: { multipart: true } do |f| %>
		<%= f.input :reader_return_date, as: :date %>
		<%= f.file_field :reader_scan, label: "Upload PDF Scan" %>
		<%= f.button :submit, class: 'btn btn-warning' %>
	<% end %>
</div>

app/views/units/_update.html.erb
<div id="unit-update">
	<h4>When Student Has Returned Unit</h4>
	<% if @unit.errors.any? %>
		<% @unit.errors.full_messages.each do |error| %>
			<p class="error_text"><%= error %></p>
		<% end %>
	<% end %>
	<%= simple_form_for @unit, url: unit_path(@unit), html: { multipart: true } do |f| %>
		<%= f.input :return_date, as: :date %>
		<%= f.file_field :scan, label: "Upload PDF Scan" %>
		<%= f.button :submit, class: 'btn btn-warning' %>
	<% end %>
</div>

app/views/units/completed_units.html.erb
<h3 style="text-align: center;">Completed</h3>

<div class="completed-units">
  <%# will_paginate @units %>

  <table id="datatable-unit" class="table table-bordered">
    <thead>
      <tr>
        <td>Student</td>
        <td>Volunteer</td>
        <td>Course</td>
        <td>Status</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @units.each do |unit| %>
        <tr class="table-row">
          <td><%= unit.prisoner.name %></td>
          <td><%= unit.volunteer.name if unit.volunteer %></td>
          <td><%= unit.course.title %></td>
          <td><%= unit.status %></td>
          <td><%= link_to "View Unit", unit_path(unit), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%# will_paginate @units %>
</div>

<script type="text/javascript">
  $("#datatable-unit").DataTable({});
</script>

app/views/units/index.html.erb
<% provide(:title, "Unit Index") %>

<div class="export-link">
	<%= link_to("Export Data", units_path(format: :csv)) %>
</div>

<h3 style="text-align: center;">Waiting on Student</h3>
<table id="datatable-unit-waiting-student" class="table table-bordered">
	<thead>
		<tr>
			<td>Student</td>
			<td>Course</td>
			<td>Course Unit</td>
			<td>Mailing Date</td>
			<td>Status</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @waiting_student.each do |unit| %>
			<tr class="table-row">
				<td><%= unit.prisoner.name %></td>
				<td><%= unit.course.try(:title) %></td>
				<td><%= unit.sub_course_abbr %></td>
				<td><%= unit.mailing_date %></td>
				<td><%= unit.status %></td>
				<td><%= link_to "Update", unit_path(unit), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3 style="text-align: center;">Unassigned Units</h3>
<table id="datatable-unit-unassigned" class="table table-bordered">
	<thead>
		<tr>
			<td>Student</td>
			<td>Course</td>
			<td>Course Unit</td>
			<td>Mailing Date</td>
			<td>Status</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @unassigned.each do |unit| %>
			<tr class="table-row">
				<td><%= unit.prisoner.name %></td>
				<td><%= unit.course.title %></td>
				<td><%= unit.sub_course_abbr %></td>
				<td><%= unit.mailing_date %></td>
				<td><%= unit.status %></td>
				<td><%= link_to "Assign", unit_path(unit), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3 style="text-align: center;">Waiting on Volunteer</h3>
<table id="datatable-unit-waiting" class="table table-bordered">
	<thead>
		<tr>
			<td>Student</td>
			<td>Volunteer</td>
			<td>Course</td>
			<td>Mailing Date</td>
			<td>Status</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @waiting.each do |unit| %>
			<tr class="table-row">
				<td><%= unit.prisoner.name %></td>
				<td><%= unit.volunteer.name if unit.volunteer %></td>
				<td><%= unit.course.title %></td>
				<td><%= unit.reader_mailing_date %></td>
				<td><%= unit.status %></td>
				<td><%= link_to "Reassign", unit_path(unit), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<hr>
<div class="completed-units-link">
	<%= link_to 'Completed Units', '/completed_units' %>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#datatable-unit-waiting-student").DataTable({});
		$("#datatable-unit-unassigned").DataTable({});
		$("#datatable-unit-waiting").DataTable({});
		$("#datatable-unit").DataTable({});
		$(".clickable-row").click(function(){
			window.document.location = $(this).data("href");
		})
	})
</script>

app/views/units/late.html.erb
<% provide(:title, "Late Units") %>

<table id="datatable-unit-late" class="table table-bordered">
	<thead>
		<tr>
			<td>Volunteer</td>
			<td>Course</td>
			<td>Course Unit</td>
			<td>Reader Mailing Date</td>
			<td>Status</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @units.each do |unit| %>
			<tr class="table-row">
				<td><%= unit.volunteer.name if unit.volunteer %></td>
				<td><%= unit.course.title if unit.course %></td>
				<td><%= unit.sub_course_abbr %></td>
				<td><%= unit.reader_mailing_date %></td>
				<td><%= unit.status %></td>
				<td><%= link_to "Reassign", unit_path(unit), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$("#datatable-unit-late").DataTable({})
	})
</script>

app/views/units/show.html.erb
<% provide(:title, "Unit #{@title if @title}") %>

<div class="col-sm-12">
	<div id="unit-box" class="clearfix">
		<div class="col-sm-5">
		<p>Student: <%= link_to @unit.prisoner.name, prisoner_path(@unit.prisoner), id: "prisoner-name" %></p>
		<p>Course: <%= @unit.course.title %></p>
		<p>Unit: <%= @unit.sub_course %></p>
		<p>Status: <%= @unit.status %></p>
		<% unless @unit.volunteer.nil? %>
			<p>Volunteer: <%= link_to @unit.volunteer.name, volunteer_path(@unit.volunteer) %></p>
		<% end %>
		</div>

		<% if @unit.scan.url %>
		<div class="col-sm-2">
			<div>Student's Submission</div>
			<div><%= link_to image_tag('pdf.png'), @unit.scan.url, id: "pdf-icon", target: "_blank" %></div>
		</div>
		<% end %>
		<% if @unit.reader_scan.url %>
			<div class="col-sm-2">
			<div>Reader's Submission</div>
			<div><%= link_to image_tag('pdf.png'), @unit.reader_scan.url, id: "pdf-icon", target: "_blank" %></div>
			</div>
		<% end %>
		<form action="/units/destroy/<%= @unit.id %>" method="get">
			<input type="submit" class="btn btn-danger" value="DELETE" onclick="return confirm('Are you sure you would like to delete this unit?')">
		</form>
	</div>
</div>

<% if @unit.status == "Waiting on Student" %>
	<div class="col-sm-12">
		<%= render 'units/update' %>
	</div>
<% elsif @unit.status == "Waiting on Volunteer" %>
	<div class="col-sm-12">
		<%= render 'units/reader_update' %>
		<div>OR if unit is late</div>
		<%= button_to "Reassign Unit", unit_assign_path(@unit, @unit.volunteer.id), method: "patch", class: "btn btn-danger" %>
	</div>
<% end %>

<div class="col-sm-12">
	<% if @unit.status == "Unassigned" %>
		<h3 style="text-align: center;">Recommended Volunteers</h3>
		<table id="datatable-volunteer-matches" class="table table-striped table-bordered">
			<thead>
				<tr>
					<td>Name</td>
					<td># Courses</td>
					<td>Last Unit (Return Date, Student)</td>
					<td>Comments</td>
					<td></td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				<% @matches.each do |match| %>
					<tr class="table-row">
						<td><%= match[:volunteer].name %> <strong><%= "(Read this students last unit)" if match[:ranking] == 100.0 %></strong></td>
						<td><%= match[:volunteer].courses.length %></td>
						<td><%= match[:volunteer].units.last.reader_return_date.strftime('%m/%d/%y') if match[:volunteer].units.last %>, <%= match[:volunteer].units.last.prisoner.name if match[:volunteer].units.last %></td>
						<td><%= match[:volunteer].comments %></td>
						<td><%= button_to "Assign & Email", unit_volunteer_assigns_path(@unit,match[:volunteer],email: "true"), class: "btn btn-primary", data: { confirm: "This will send the reader an email with the student's work attached" } %></td>
						<td><%= button_to "Assign", unit_volunteer_assigns_path(@unit,match[:volunteer]), class: "btn btn-primary", data: { confirm: "This will NOT send the reader an email, it must be mailed" } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#datatable-volunteer-matches").DataTable({
			"ordering": false
		});
	});
</script>