config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :courses, except: [:show]

  resources :sessions, only: [:create, :new, :destroy]

  resources :certificate, only: :index

  resources :prisoners, only: [:create, :update, :show, :index, :edit] do
    resources :units, only: [:create, :update]
  end

  resources :volunteers, only: [:create, :update, :show, :index, :edit]

  resources :units, only: [:update, :show, :index] do
    resources :assigns, only: :update
    resources :volunteers, only: [:show] do
      resources :assigns, only: [:create]
    end
  end
  get 'completed_units' => 'units#completed_units'

  get 'reports/attrs' => 'reports#attrs'
  resources :reports, only: [:index, :show, :create, :new, :destroy]

  get '/sub_course/:id' => 'units#find_sub_courses'
  post '/dictionary' => 'prisoners#dictionary'
  post '/vacation' => 'volunteers#vacation'
  get '/waitlist' => 'prisoners#waitlist'
  get '/late/:days' => 'units#late'
  post '/:prisoner_id/certificate' => 'certificate#create'
  get '/course_overview' => 'static_pages#courses'
  post '/delete_vacation' => 'volunteers#delete_vacation'

  get '/units/destroy/:id' => "api/units#destroy"

end

app/models/prisoner.rb
require 'csv'

class Prisoner < ActiveRecord::Base
	#Associations
	has_many :units, inverse_of: :prisoner, dependent: :destroy
	has_many :volunteers, through: :units
	has_many :certificates, dependent: :destroy
	has_and_belongs_to_many :courses

	#validations
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :prison_id, presence: true
	validates :address_1, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zip, presence: true

	def self.to_csv
		attributes = %w{first_name last_name address_1 prison_id enrollment_date city state comments created_at}

		CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |prisoner|
        csv << attributes.map{ |attr| prisoner.send(attr) }
      end
    end
	end

	def self.report_rows
    %w(first_name last_name city state enrollment_date)
  end

  def self.active(startDate, endDate)
		self.select { |x| x.units.first.created_at > start && x.units.first.created_at < endDate } 	
  end

	def name
		"#{first_name} #{last_name}"
	end

	def full_address_1
		address_2 ? "#{address_1} + #{address_2}" : address_1
	end

	def full_address_2
		"#{city} #{state} #{zip}"
	end

	def courses_with_subcourses
		hash = Hash.new()
		units.each do |x|
			if x.course
				hash[x.course.title] = [] if hash[x.course.title].nil?
			end
			if x.course
				hash[x.course.title].push(x.sub_course) unless hash[x.course.title].include? x.sub_course
			end
		end
		hash
	end

	def courses_with_all_subcourses
		hash = Hash.new()
		units.each do |x|
			if x.course
				hash[x.course.title] = x.course.sub_courses if hash[x.course.title].nil?
			end
		end
		hash
	end

	def last_volunteer
		units ? units.last(2)[0].volunteer : nil
	end
end

app/controllers/prisoners_controller.rb
class PrisonersController < ApplicationController

  def create
  	@prisoner = Prisoner.new(prisoner_params)
  	if @prisoner.save
  		redirect_to @prisoner
  	else
  		render 'new'
  	end
  end

  def update
    @prisoner = Prisoner.find(params[:id])
    if @prisoner.update_attributes(prisoner_params)
      redirect_to @prisoner
    else
      render 'edit'
    end
  end

  def show
  	@prisoner = Prisoner.find(params[:id])
    @unit = @prisoner.units.build
    @units = @prisoner.units
    @courses = @prisoner.courses_with_subcourses
    @all_courses = @prisoner.courses_with_all_subcourses
    @certificate = @prisoner.certificates.build
  end

  def index
    @prisoners = Prisoner.all.select { |x| x.enrollment_date }

    respond_to do |format|
      format.html
      format.csv { send_data Prisoner.to_csv, filename: "students-#{Date.today}.csv" }
    end
  end

  def edit
    @prisoner = Prisoner.find(params[:id])
  end

  def dictionary
    @prisoner = Prisoner.find(params[:prisoner][:id])
    @prisoner.update_attribute(:dictionary, true)
    @prisoner.update_attribute(:dictionary_sent, Date.today())
    redirect_to @prisoner
  end

  def waitlist
    @prisoners = Prisoner.all.select { |x| x.enrollment_date.nil? }
  end

  private

  	def prisoner_params
  		params.require(:prisoner).permit(:first_name, :last_name, :address_1,
		    :address_2, :prison_id, :waitlist_date, :city, :state, :zip, :dictionary_sent, :comments, :enrollment_date)
  	end

end

app/views/prisoners/_new.html.erb
<div class="form-wrapper">
	<h4>Add Student to Database</h4>
	<% if @prisoner.errors.any? %>
		<% @prisoner.errors.full_messages.each do |error| %>
			<span class="error_text"><%= error %></span>
		<% end %>
	<% end %>
	<%= simple_form_for @prisoner do |f| %>
			<%= f.input :first_name, label: 'First Name' %>
			<%= f.input :last_name, label: 'Last Name' %>
			<%= f.input :prison_id, label: 'Prisoner ID' %>
			<%= f.input :waitlist_date, as: :date %>
			<%= f.input :address_1, label: 'Address Line 1' %>
			<%= f.input :address_2, label: 'Address Line 2', required: false %>
			<%= f.input :city %>
			<%= f.input :state, collection: us_states %>
			<%= f.input :zip %>
			<%= f.button :submit, 'Save' , class: 'pull-right btn-lg btn-primary' %>
	<% end %>
</div>

app/views/prisoners/edit.html.erb
<% provide(:title, "Edit Student") %>
<%= render 'prisoners/new' %>

app/views/prisoners/index.html.erb
<% provide(:title, "Student Index") %>

<div class="export-link">
	<%= link_to("Export Data", prisoners_path(format: :csv)) %>
</div>

<table id="datatable-prisoner" class="table table-striped table-bordered">
	<thead>
		<tr>
			<td>First Name</td>
			<td>Last Name</td>
			<td>City</td>
			<td>State</td>
			<td>Street Address</td>
			<td>Enrollment Date</td>
			<td>Comments</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @prisoners.each do |prisoner| %>
			<tr class="table-row">
				<td><%= prisoner.first_name %></td>
				<td><%= prisoner.last_name %></td>
				<td><%= prisoner.city %></td>
				<td><%= prisoner.state %></td>
				<td><%= prisoner.full_address_1 %><br><%= prisoner.full_address_2 %></td>
				<td><%= prisoner.enrollment_date %></td>
				<td><%= prisoner.comments %></td>
				<td><%= link_to "Profile", prisoner_path(prisoner), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$("#datatable-prisoner").DataTable({})
	})
</script>

app/views/prisoners/new.html.erb
<%= render 'prisoners/new' %>

app/views/prisoners/show.html.erb
<% provide(:title, 'Student Profile') %>

<div class="envelope-tab">
	<%= link_to "Edit", edit_prisoner_path(@prisoner), class: "btn btn-primary" %>
</div>

<div class="envelope clearfix">
	<div class="col-sm-2"><img src="https://s3.amazonaws.com/collegeguild/vol_profile.jpg" class="img-responsive"></div>
	<div class="col-sm-10 basic-info">
		<div>Name: <%= @prisoner.name %></div>
		<div>ID: <%= @prisoner.prison_id %></div>
		<div>
			<span>Address:</span> 
			<span>
				<%= @prisoner.full_address_1 %><br>
				<%= @prisoner.full_address_2 %>
			</span>
		</div>
		<div>Comments: <%= @prisoner.comments %></div>
		<div>Dictionary Sent: <%= @prisoner.dictionary ? "Yes #{@prisoner.dictionary_sent.strftime('%m/%d/%y')}" : "No" %></div>
	</div>
	<% unless @prisoner.enrollment_date %>
		<div class="col-sm-12">
			 <%= simple_form_for @prisoner, url: "/prisoners/#{@prisoner.id}", method: 'patch' do |f| %>
			 	<input type="hidden" name="prisoner[enrollment_date]" value="<%= Date.today() %>">
				<%= f.submit 'Take off Waitlist', class: "btn btn-primary" %>
			<% end %>
		</div>
	<% end %>
	<div class="col-sm-12">
		<h3 style="text-align: center;">Add Unit</h3>
		<%= render 'units/create' %>
	</div>
	<% if @units %>
		<div class="col-sm-12">
			<h3 style="text-align: center; margin-top: 10px;">Units</h3>
			<table id="prisoner-show-table" class="table table-bordered">
				<thead>
					<tr>
						<td>Reader Name</td>
						<td>Status</td>
						<td>Course</td>
						<td>Course Unit</td>
						<td>Mailing Date</td>
						<td>Return Date</td>
						<td></td>
					</tr>
				</thead>
				<tbody>
					<% @units.each do |unit| %>
						<% unless unit.course.nil? %>
						<tr>
							<td><%= unit.volunteer.name if unit.volunteer %></td>
							<td><%= unit.status %></td>
							<td><%= unit.course.title if unit.course %></td>
							<td><%= unit.sub_course %></td>
							<td><%= unit.mailing_date.strftime('%m/%d/%y') if unit.mailing_date %></td>
							<td><%= unit.return_date.strftime('%m/%d/%y') if unit.return_date %></td>
							<td><%= link_to "Unit Page", unit_path(unit), class: "btn btn-primary" %></td>
						</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>
	<div class="col-sm-12">
		<div class="update-comments">
			<%= simple_form_for @prisoner, url: "/prisoners/#{@prisoner.id}", method: 'patch' do |f| %>
				<%= f.input :comments, as: :text %>
				<%= f.submit 'Update Comments', class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
	<% unless @prisoner.dictionary %>
		<div class="col-sm-12">
			<div id="add-dictionary">
				<p>Submit when a dictionary has been sent</p>
				<%= simple_form_for @prisoner, url: "/dictionary", method: 'post' do |f| %>
					<input name="prisoner[id]" type="hidden" value="<%= @prisoner.id %>">
					<%= f.submit 'Dictionary Sent', class: "btn btn-primary" %>
				<% end %>
			</div>
		</div>
	<% end %>
	<div class="col-sm-12">
		<div id="course-completion">
			<h3 style="text-align: center;">Course Completion</h3>
			<% puts @courses %>
			<% @all_courses.each do |course, sub_courses| %>
				<div class="col-sm-4">
					<div class="course-block">
						<h4><%= course %></h4>
						<% sub_courses.each do |sub_course| %>
							<% status = nil %>
							<% @prisoner.units.each do |unit| %>
								<% if unit.course %>
									<% if unit.course.title == course && unit.sub_course == sub_course %>
										<% unit.status == "Completed" ? status = "course-completed" : "in-progress" %>
									<% end %>
								<% end %>
							<% end %>
							<div class="<%= status %>"><%= sub_course %></div>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-sm-12">
		<% if @prisoner.certificates.length > 1 %>
			<h3 style="text-align: center">Certificates</h3>
			<% @prisoner.certificates.each do |cert| %>
				<% if cert.id %>
					<div class="col-sm-4">
						<div class="cert-box">
							<h5>Course: <%= cert.course.title %></h5>
							<p>Mailing Date: <%= cert.mailing_date.strftime('%m/%d/%y') %></p>
						</div>
					</div>
				<% end %>
			<% end %>
		<% end %> 
	</div>
	<div class="col-sm-12">
		<h3 style="text-align: center;">Add Certificate</h3>
		<div id="add-certificate">
			<%= simple_form_for @certificate, url: ('/' + @prisoner.id.to_s + '/certificate'), method: 'post' do |f| %>
				<%= f.association :course, as: :select %>
				<%= f.button :submit, class: 'btn btn-warning' %>
			<% end %>
		</div>
	</div>
	<div class="col-sm-12" id="volunteer-list">
		<h3>Volunteers</h3>
		<% @prisoner.volunteers.uniq.each do |volunteer| %>
			<div class="name-bar" id="name-bar-<%= volunteer.id %>">
				<%= volunteer.name %>
				<span class="glyphicon glyphicon-menu-down"></span>
			</div>
			<div class="hidden-info" id="hidden-name-bar-<%= volunteer.id %>">
				<%= volunteer.email %><br>
			</div>
		<% end %>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#volunteer-list .name-bar").click(function(){
			var id = $(this).attr("id");
			$("#hidden-" + id).toggle();
		});
		$("#prisoner-show-table").DataTable({})
	})
</script>

app/views/prisoners/waitlist.html.erb
<% provide(:title, "Waitlist") %>

<h3 style="text-align: center;">Current Waitlist Length: <%= @prisoners.length %></h3>

<table id="waitlist" class="table table-striped table-bordered">
	<thead>
		<tr>
			<td>Name</td>
			<td>Address</td>
			<td>Prisoner ID</td>
			<td>Waitlist Date</td>
			<td>Comments</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @prisoners.each do |prisoner| %>
			<tr class="table-row">
				<td><%= prisoner.name %></td>
				<td><%= prisoner.full_address_1 %><br><%= prisoner.full_address_2 %></td>
				<td><%= prisoner.prison_id %></td>
				<td><%= prisoner.waitlist_date %></td>
				<td><%= prisoner.comments %></td>
				<td><%= link_to "Profile", prisoner_path(prisoner), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$("#waitlist").DataTable({})
	})
</script>