config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :courses, except: [:show]

  resources :sessions, only: [:create, :new, :destroy]

  resources :certificate, only: :index

  resources :prisoners, only: [:create, :update, :show, :index, :edit] do
    resources :units, only: [:create, :update]
  end

  resources :volunteers, only: [:create, :update, :show, :index, :edit]

  resources :units, only: [:update, :show, :index] do
    resources :assigns, only: :update
    resources :volunteers, only: [:show] do
      resources :assigns, only: [:create]
    end
  end
  get 'completed_units' => 'units#completed_units'

  get 'reports/attrs' => 'reports#attrs'
  resources :reports, only: [:index, :show, :create, :new, :destroy]

  get '/sub_course/:id' => 'units#find_sub_courses'
  post '/dictionary' => 'prisoners#dictionary'
  post '/vacation' => 'volunteers#vacation'
  get '/waitlist' => 'prisoners#waitlist'
  get '/late/:days' => 'units#late'
  post '/:prisoner_id/certificate' => 'certificate#create'
  get '/course_overview' => 'static_pages#courses'
  post '/delete_vacation' => 'volunteers#delete_vacation'

  get '/units/destroy/:id' => "api/units#destroy"

end

app/views/layouts/_header.html.erb
<header>
	<div id="header">
		<div id="banner"><h1>COLLEGE GUILD</h1></div>
		<div>
			<div>respect</div>
			<div>reduces</div>
			<div>recidivism</div>
		</div>
		<%= button_to "Logout", session_path(@current_user), method: :delete, class: 'btn btn-primary' %>
	</div>
</header>

<div id="page-title">
	<h2><%= yield(:title) %> Page</h2>
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
	<div id="logo">
		<svg width="148px" height="220px" viewBox="39 -13 148 220" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
		    <defs></defs>
		    <g id="Group" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" transform="translate(39.000000, -13.000000)" font-size="125" font-family="Avenir-Book, Avenir" letter-spacing="6.94444418" font-weight="normal">
		        <text id="C" fill="#769FCC">
		            <tspan x="0" y="125">C</tspan>
		        </text>
		        <text id="G" fill="#769FCC">
		            <tspan x="43" y="174">G</tspan>
		        </text>
		    </g>
		</svg>
	</div>

	<nav>
		<div class="nav-link"><%= link_to 'Home', root_path %></div>
		<div class="nav-link"><%= link_to 'Students', prisoners_path %></div>
		<div class="nav-link"><%= link_to 'Volunteers', volunteers_path %></div>
		<div class="nav-link"><%= link_to 'Units', units_path %></div>
		<div class="nav-link"><%= link_to 'Waitlist', '/waitlist' %></div>
		<div class="nav-link"><%= link_to 'Late Units', '/late/7' %></div>
		<div class="nav-link"><%= link_to 'Courses', '/course_overview' %></div>
		<div class="nav-link"><%= link_to 'Reports', reports_path %></div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollegeGuild</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/CG_logo.png' %>
</head>
<body>

<%= render 'layouts/sidebar' %>


<div id="content-wrapper">
	<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
      	<div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollegeGuild</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>
</head>
<body>

<div id="login-wrapper">
	<% flash.each do |message_type, message| %>
      	<div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
	<%= yield %>
</div>

</body>
</html>